### PR TITLE
New config option for minimap delay 

### PR DESCRIPTION
**Pull request by wessel1608**
Increase delay manually in case automatically starting is not working.

### CODE REVIEW

**Comment by Dementor42** [comment]
Hey @wessel1608 thanks for your PR.

I think instead of making the timeout an config option, we should make the max number of checks an option. (`max_minimap_detection_tries´).

P.S.: Could you squash your commits to one commit and name it more descriptive? Thanks

**Comment by wessel1608** [comment]
How do i merge te commits?

**Comment by Dementor42** [comment]
https://stackoverflow.com/questions/5189560/squash-my-last-x-commits-together-using-git

**Comment by Dementor42** [comment]
Added in 3cb36d74b399fb0a8234d073e5c08c2f26852e94, will be released soon™

**Pull request closed without merging**
